fail_fast: true
repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: poetry run black .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: mypy
        name: MyPy
        entry: poetry run mypy gentooinstall --show-error-codes
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: pylint
        name: Pylint
        entry: poetry run pylint -j 4 gentooinstall
        pass_filenames: false
        language: system
